### ISSUE TITLE
Please define "Blockchain" more clearly

### ISSUE THREAD

**Issue by rohieb** [dzuk-mutant/digital-abundance-license#1]
Quoting [Wikipedia](https://en.wikipedia.org/w/index.php?title=Blockchain&oldid=1063642010):

> A blockchain is a growing list of records, called blocks, that are linked together using cryptography.[1][2][3][4] Each block contains a cryptographic hash of the previous block, a timestamp, and transaction data (generally represented as a Merkle tree). The timestamp proves that the transaction data existed when the block was published in order to get into its hash. As blocks each contain information about the block previous to it, they form a chain, with each additional block reinforcing the ones before it. Therefore, blockchains are resistant to modification of their data because once recorded, the data in any given block cannot be altered retroactively without altering all subsequent blocks.

As per this definition, Git itself would count as a blockchain, as it is based on the idea of a Merkle Tree (see for example [this primer on Git objects](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects)), but I guess that this definition would not be in the spirit of this license. As far as I know, there are also other blockchains which are purely based on the idea of Merkle Trees, and not based on Proof of Work or Proof of Stake, and therefore do not have the disadvantages mentioned in the beginning of the README:

> They waste vasts amount of electricity and reversing strides to reduce carbon emissions, they provide no actual benefit to normal people but provide many benefits to unscrupulous businesspeople and organised criminals, and they do nothing that less wasteful computer systems cannot do.

Please specify if the License should forbid usage in such systems.

**Comment by rohieb** [comment]
> As far as I know, there are also other blockchains which are purely based on the idea of Merkle Trees, and not based on Proof of Work or Proof of Stake

Hyperledger was such a system I was thinking of. It supports multiple algorithms to achieve consensus between the nodes for byzantine fault-tolerance, and does not rely on Proof of Work or Proof of Stake.

**Comment by dzuk-mutant** [comment]
I had some more thoughts generally about where to go with this license and I think it might be more worthwhile to target the semantics of these systems than the underlying logic, because that's where a lot of what I see as the issue lies.

So at least for now unless there's a better way to target the kind of gas-guzzling blockchains like Bitcoin, this license has been renamed the Digital Abundance License and targets digital scarcity systems instead of blockchains.
